#!/bin/sh
while read -r file
do
        case "$1" in
        "w") setbg "$file" & ;;
	"D") mv "$file" ~/.trash ;;
	"j") jp2a "$file" ;;
	"i") convert -negate "$file" "$file" ;;
	"g") gimp "$file" ;;
        esac
done
