#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#  [ -x "$f" ] && . "$f"
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
# Activate dbus variables
dbus-update-activation-environment --all
#dbus-launch dwm
while true; do
echo "test"
echo "test"
	#fix escape
	inputmaps &
        #setxkbmap -option caps:swapescape &
	#start dwm
	#sleep 3 && setTheme &
	setTheme && dwm 2> ~/.dwm.log
done
