#!/bin/sh
while read -r file
do
        case "$1" in
        "w") feh --bg-fill $file && echo "set image to $file" & ;;
	"D") mv "$file" ~/.trash ;;
	#"j") jp2a "$file" ;;
	"i") convert -negate "$file" "$file" ;;
	"G") gimp "$file" ;;
	"y")
		printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        esac
done
